// Code generated by "enumer -type=Suit -trimprefix S"; DO NOT EDIT.

//
package playingcard

import (
	"fmt"
)

const _SuitName = "WILDCLUBSDIAMONDSHEARTSSPADES"

var _SuitIndex = [...]uint8{0, 4, 9, 17, 23, 29}

func (i Suit) String() string {
	if i >= Suit(len(_SuitIndex)-1) {
		return fmt.Sprintf("Suit(%d)", i)
	}
	return _SuitName[_SuitIndex[i]:_SuitIndex[i+1]]
}

var _SuitValues = []Suit{0, 1, 2, 3, 4}

var _SuitNameToValueMap = map[string]Suit{
	_SuitName[0:4]:   0,
	_SuitName[4:9]:   1,
	_SuitName[9:17]:  2,
	_SuitName[17:23]: 3,
	_SuitName[23:29]: 4,
}

// SuitString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SuitString(s string) (Suit, error) {
	if val, ok := _SuitNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Suit values", s)
}

// SuitValues returns all values of the enum
func SuitValues() []Suit {
	return _SuitValues
}

// IsASuit returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Suit) IsASuit() bool {
	for _, v := range _SuitValues {
		if i == v {
			return true
		}
	}
	return false
}
