// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package games

import (
	"github.com/rhino1998/codenames/games/liarspoker"
)

type LiarsPokerPlayerCallInput struct {
	Player string             `json:"player"`
	Call   []*liarspoker.Card `json:"call"`
}
