schema:
    - games/schema.graphql
    - games/*/schema.graphql
documents: ''
extensions:
  codegen:
    generates:
      frontend/graphql_schema.json:
        - introspection
      frontend/fragmentTypes.json:
        - fragment-matcher
