codenames:
  word_lists:
      words: words.txt
      pokemon: pokemon.txt
      myths: myths.txt
      countries: countries.txt
      counties: counties.txt
      currency: currency.txt
      hard: hard.txt
      dewey: dewey.txt
port: 9000
